dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - docker
cache:
  pip: true
install:
  - pip install pipenv codacy-coverage
  - make
script:
  - make lint
  - make coverage
after_success:
  - pipenv run coverage xml
  - python-codacy-coverage
notifications:
  email: false
