sudo: required

language: python

python:
  - 3.4
  - 3.5

cache: pip

git:
  submodules: false

services:
  - docker

before_install:
  - sudo apt-get -y --purge remove docker-engine
  - sudo apt-get -y install docker-engine
  - docker --version

install:
  - pip install -r requirements/development.txt
  - make docker-image

script:
  - flake8
  - ./manage.py test --verbosity 2
