sudo: required

language: python

python:
  - 3.4
  - 3.5

cache: pip

git:
  submodules: false

services:
  - docker

before_install:
  - sudo apt-get -y --purge remove docker-engine
  - sudo apt-get -y install docker-engine
  - docker --version

install:
  - pip install -r requirements/main.txt
  - pip install -r requirements/test.txt -r requirements/lint.txt
  - (cd tests/functional/testrunner && docker build -t inloop-integration-test .)
  - mkdir -p .state

script:
  - flake8
  - isort --check-only
  - coverage run manage.py test --verbosity 2

after_success:
  - coverage report
