dist: bionic

language: python

os: linux

jobs:
  include:
  - name: Python 3.7 tests
    python: 3.7
    services: docker
    env: NOXSESSION=tests-3.7
  - name: Python 3.6 tests
    python: 3.6
    services: docker
    env: NOXSESSION=tests-3.6
  - name: Python linting
    python: 3.6
    env: NOXSESSION=lint

cache: pip

install: pip install -r build-requirements.txt

script: nox
