sudo: false
language: python
git:
  submodules: false
  depth: 1
services:
  - docker
cache:
  pip: true
install:
  - pip install -U pip setuptools
  - pip install -U tox
before_script:
  - pip freeze
script:
  - tox
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=xlint
