sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
git:
  submodules: false
  depth: 1
services:
  - docker
cache:
  pip: true
env:
  - TARGET=xlint
  - TARGET=coveragetest
install:
  - pip install -U pip setuptools
  - make install-deps
before_script:
  - pip freeze
script:
  - make $TARGET
after_success:
  - if [[ $TARGET == coveragetest ]]; then coverage report; fi
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.6"
  exclude:
    - python: "3.4"
      env: TARGET=xlint
    - python: "3.6"
      env: TARGET=xlint
