dist: bionic

language: python

os: linux

jobs:
  include:
  - python: 3.7
    env: NOXSESSION=tests-3.7
  - python: 3.6
    env: NOXSESSION=tests-3.6
  - python: 3.6
    env: NOXSESSION=lint

services:
- docker

cache: pip

install:
- pip install -r build-requirements.txt
- docker build -t inloop-integration-test tests/testrunner

script: nox
