sudo: false

language: python

python:
  - 3.4
  - 3.5

cache: pip

git:
  submodules: false

services:
  - docker

install:
  - pip install -r requirements/main.txt
  - pip install -r requirements/test.txt -r requirements/lint.txt
  - (cd tests/functional/testrunner && docker build -t inloop-integration-test .)
  - mkdir -p .state

before_script:
  - pip freeze
  - docker --version

script:
  - flake8
  - isort --check-only
  - coverage run manage.py test --verbosity 2

after_success:
  - coverage report
