dist: bionic

language: python

os: linux

jobs:
  include:
  - python: 3.7
    services: docker
    env: NOXSESSION=tests-3.7
  - python: 3.6
    services: docker
    env: NOXSESSION=tests-3.6
  - python: 3.6
    env: NOXSESSION=lint

cache: pip

install: pip install -r build-requirements.txt

script: nox
